services:
  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000" # Port backend
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./frontend/public/pfp:/app/frontend/public/pfp  # Map the uploads directory
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_HOST: db
      REDIS_URL:
      PORT: 3000
    depends_on:
      - db
    env_file:
      - ./backend/.env


  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173" # Port frontend (default Vite)
    volumes:
      - ./frontend:/app
      - /app/node_modules

  db:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./backend/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  # redis:
  #   image: redis:latest
  #   container_name: redis_container
  #   ports:
  #     - "6379:6379"

volumes:
  pg_data:
